# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'snowflake' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for snowflake

  target 'snowflake-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'snowflakeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'snowflake-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for snowflake-tvOS

  target 'snowflake-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
