# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'petstorage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for petstorage

  target 'petstorage-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'petstorageTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'petstorage-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for petstorage-tvOS

  target 'petstorage-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
